# Bismillah
##### 12-06-2026 
##### aj hum numpy start karain gy


##### There are 2 type of 
- Data Engineering
- Data Analytics

 ##### Libraries we will cover in this section
 - NumPy
 - Pandas
 - Data Visualization
 - Statistics

In [11]:
import numpy as np
import pandas as pd


In [2]:
# creating a numpy array using a list

arr1 = np.array([1,2,3,4,5,6,7,8,9])

In [3]:
len(arr1)

9

In [4]:
type(arr1)

numpy.ndarray

In [5]:
arr1.ndim

1

In [17]:
arr2d = np.array([[1,2,3,4] , [2,3,4,5] , [3,4,5,6]])

In [18]:
arr2d

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

In [19]:
arr2d.shape

(3, 4)

In [20]:
# arr2d = pd.DataFrame(arr2d)
arr2d

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

In [21]:
arr1.ndim , arr2d.ndim

(1, 2)

In [22]:
arr1.shape

(9,)

In [30]:
arr2d = np.arange(20).reshape(5,4)
arr2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [31]:
arr1.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
arr2d.reshape(2,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])