# Vectorized Operations

In [1]:
lst1 = [1,3,5,7,9]
lst2 = [2,4,6,8,10]
lst1 + lst2

[1, 3, 5, 7, 9, 2, 4, 6, 8, 10]

In [2]:
lst3 = []
for n in zip(lst1 , lst2):
    lst3.append(sum(n))
lst3

[3, 7, 11, 15, 19]

In [3]:
list(zip(lst1, lst2))

[(1, 2), (3, 4), (5, 6), (7, 8), (9, 10)]

In [4]:
lst4 = []
for a in lst1:
   lst4.append( a*10)
lst4

[10, 30, 50, 70, 90]

In [21]:
import numpy as np
import random

arr1 = np.array(lst1)

arr2 = np.array(lst2)

In [6]:
arr1*10

array([10, 30, 50, 70, 90])

In [7]:
arr1

array([1, 3, 5, 7, 9])

In [8]:
arr2

array([ 2,  4,  6,  8, 10])

In [9]:
arr1+arr2

array([ 3,  7, 11, 15, 19])

In [14]:
arr2d_1 = np.arange(1, 17).reshape(4,4)
arr2d_2 = np.arange(17,33).reshape(4,4)


# -This is what we call Mirror Addition

In [15]:
arr2d_1 + arr2d_2

array([[18, 20, 22, 24],
       [26, 28, 30, 32],
       [34, 36, 38, 40],
       [42, 44, 46, 48]])

In [16]:
arr2d_1*50 + arr2d_2

array([[ 67, 118, 169, 220],
       [271, 322, 373, 424],
       [475, 526, 577, 628],
       [679, 730, 781, 832]])

# Artihmetic Operation on array
- Addition
- Subtraction
- Multiplication >>> (Linear Algebra) aur eik (Mirror)

In [18]:
a = np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [28]:
b = np.random.randn(4,3)*10



In [29]:
b

array([[ -6.90292123,  -8.73364988, -21.3498573 ],
       [-12.55547849,   2.92400741,   3.42336017],
       [ 17.50679941,  -2.75853642,  -0.12546836],
       [ 13.9729003 ,   3.95034177,  -3.32220802]])

# becuase matrices ka rule hai, eik matrix ka row and 2nd ka colum same hone chahiye hain, is lea hum isko is tarhan sy multiply kr lain gy


In [32]:
a@b

array([[  76.39812122,    4.64012274,  -28.16837411],
       [ 124.48332119,  -13.83122576, -113.66506815],
       [ 172.56852115,  -32.30257425, -199.1617622 ]])

## eik method numpy main hamaray pass hota hai, dot mehtod

In [34]:
a.dot(b)

array([[  76.39812122,    4.64012274,  -28.16837411],
       [ 124.48332119,  -13.83122576, -113.66506815],
       [ 172.56852115,  -32.30257425, -199.1617622 ]])

In [35]:
b@a


array([[-242.71988634, -279.70631475, -316.69274316, -353.67917157],
       [  32.87480009,   26.66668918,   20.45857826,   14.25046735],
       [   2.58490206,   17.20769668,   31.83049131,   46.45328594],
       [   3.82473698,   18.42577103,   33.02680507,   47.62783912]])

## .ones method add ones in array

In [36]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [37]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [40]:
np.ones_like(a) # it copies dtype and shape from the other array

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

# next method zeros

In [41]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [43]:
np.zeros_like(b)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [46]:
np.empty(5)

array([2.82605581e-315, 0.00000000e+000, 2.80135039e-315, 2.81053575e-315,
       0.00000000e+000])

In [47]:
np.empty((3,6))

array([[2.82676212e-315, 0.00000000e+000, 6.26333973e-310,
        6.26333973e-310, 6.26333973e-310, 6.26333973e-310],
       [6.26333974e-310, 6.26333974e-310, 6.26333974e-310,
        6.26333974e-310, 6.26333974e-310, 6.26333974e-310],
       [6.26333974e-310, 6.26333974e-310, 6.26333974e-310,
        6.26333974e-310, 6.26333974e-310, 6.26333974e-310]])

In [48]:
np.ones((5,5))*9

array([[9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.]])

In [49]:
np.full((5,5),9)

array([[9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9]])

In [50]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [51]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Boolean Indexing

In [99]:
arr2d = np.arange(101,151).reshape(5,10)
arr2d

array([[101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
       [111, 112, 113, 114, 115, 116, 117, 118, 119, 120],
       [121, 122, 123, 124, 125, 126, 127, 128, 129, 130],
       [131, 132, 133, 134, 135, 136, 137, 138, 139, 140],
       [141, 142, 143, 144, 145, 146, 147, 148, 149, 150]])

In [54]:
arr2d > 130

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [56]:

arr2d = np.random.random_integers(1,101, 100)
arr2d

/tmp/ipykernel_16491/540571054.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 101 + 1) instead
  arr2d = np.random.random_integers(1,101, 100)


array([ 80,  23,  86,  25,  81,   7,  39,  92,  51,  58,  91,  11,  52,
        29,  73,  95,  27,  70,  26,  49,  84,  15,  35, 101,  82,  31,
        51,  37,  13,  34,  70,  83,  24,  71,  50,  39,  67,  23,  20,
        86,  24,  75,  65,  74,   5,  97,   8,  60,   1,  55,   4,  27,
        90,  95,  71,  82,  88,  61,  56,  70,  70,  99,  85,  70,  35,
        64,  78,   6,  67,  19,  54,  23,  10,  47,  25,  38,  94,  63,
        15,  24,  60,  51,  77,  81, 101,  94,  74,  53,  47,  26,  49,
        81,  93,  54,  75,  19,  99,  35,  22,  77])

In [59]:
arr1d = np.random.random_integers(1,21,20)
arr1d

/tmp/ipykernel_16491/3497706411.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 21 + 1) instead
  arr1d = np.random.random_integers(1,21,20)


array([10,  3, 19,  4,  6, 10, 15,  8, 12,  9,  6,  1,  5,  2,  4, 11, 15,
       17, 14, 10])

In [60]:
arr1d [arr1d >= 10]
# is condition ma >= 10 select karega ga given array say

array([10, 19, 10, 15, 12, 11, 15, 17, 14, 10])

In [62]:
arr1d [~(arr1d >= 10)]
# isme bhi condition same he rahe gi lakin, ~ (tilt) ka use krte 
# isko chor kr baqi sub select kar lega


array([3, 4, 6, 8, 9, 6, 1, 5, 2, 4])

In [65]:
arr1d[arr1d%2==0]
# ishe array say sub even numbers select kardo

array([10,  4,  6, 10,  8, 12,  6,  2,  4, 14, 10])

In [67]:
arr1d[(arr1d>5) & (arr1d<10)]
# isme wo numbers ayin gy to 5 aur 10 k darmian ma hoon ge


array([6, 8, 9, 6])

# to sabit yeh hua k hum multiple conditions pr bhi kam kar sakte hain using usefull librariy


# Fancy Indexing

TypeError: only length-1 arrays can be converted to Python scalars

In [69]:
arr2d[[5,1,3,1]]

array([ 7, 23, 25, 23])

In [74]:
arr2d


array([ 80,  23,  86,  25,  81,   7,  39,  92,  51,  58,  91,  11,  52,
        29,  73,  95,  27,  70,  26,  49,  84,  15,  35, 101,  82,  31,
        51,  37,  13,  34,  70,  83,  24,  71,  50,  39,  67,  23,  20,
        86,  24,  75,  65,  74,   5,  97,   8,  60,   1,  55,   4,  27,
        90,  95,  71,  82,  88,  61,  56,  70,  70,  99,  85,  70,  35,
        64,  78,   6,  67,  19,  54,  23,  10,  47,  25,  38,  94,  63,
        15,  24,  60,  51,  77,  81, 101,  94,  74,  53,  47,  26,  49,
        81,  93,  54,  75,  19,  99,  35,  22,  77])

In [75]:
arr2d[[2,10],[5,2,0]]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [77]:
arr2d

array([ 80,  23,  86,  25,  81,   7,  39,  92,  51,  58,  91,  11,  52,
        29,  73,  95,  27,  70,  26,  49,  84,  15,  35, 101,  82,  31,
        51,  37,  13,  34,  70,  83,  24,  71,  50,  39,  67,  23,  20,
        86,  24,  75,  65,  74,   5,  97,   8,  60,   1,  55,   4,  27,
        90,  95,  71,  82,  88,  61,  56,  70,  70,  99,  85,  70,  35,
        64,  78,   6,  67,  19,  54,  23,  10,  47,  25,  38,  94,  63,
        15,  24,  60,  51,  77,  81, 101,  94,  74,  53,  47,  26,  49,
        81,  93,  54,  75,  19,  99,  35,  22,  77])

In [80]:
int(arr2d.sum())

5443

In [83]:
arr2d.argmax()

np.int64(23)

In [84]:
arr2d.argmin()

np.int64(48)

In [85]:
arr1d.cummsum()


AttributeError: 'numpy.ndarray' object has no attribute 'cummsum'

In [87]:
arr1d.cumsum()

array([ 10,  13,  32,  36,  42,  52,  67,  75,  87,  96, 102, 103, 108,
       110, 114, 125, 140, 157, 171, 181])

In [90]:
np.unique(arr1d)


array([ 1,  2,  3,  4,  5,  6,  8,  9, 10, 11, 12, 14, 15, 17, 19])

# Topic : Linear Algebra

In [91]:
from numpy.linalg import inv, qr

In [107]:
arr2d = arr2d[:,:-1]
arr2d

array([[101, 102, 103, 104, 105, 106, 107],
       [111, 112, 113, 114, 115, 116, 117],
       [121, 122, 123, 124, 125, 126, 127],
       [131, 132, 133, 134, 135, 136, 137],
       [141, 142, 143, 144, 145, 146, 147]])

In [108]:
inv(arr2d)

LinAlgError: Last 2 dimensions of the array must be square

In [104]:
inv(arr2d)

LinAlgError: Last 2 dimensions of the array must be square

In [112]:
arr = np.array([[1.2,2.4,3.5,4.2,5.0,6.9] , [1.2,2.4,3.5,4.2,5.0,6.9]])

In [113]:
arr

array([[1.2, 2.4, 3.5, 4.2, 5. , 6.9],
       [1.2, 2.4, 3.5, 4.2, 5. , 6.9]])

In [116]:
q , r =  qr(arr)
q

array([[-0.70710678, -0.70710678],
       [-0.70710678,  0.70710678]])

In [117]:
r

array([[-1.69705627e+00, -3.39411255e+00, -4.94974747e+00,
        -5.93969696e+00, -7.07106781e+00, -9.75807358e+00],
       [ 0.00000000e+00,  4.53784618e-17,  4.86953585e-16,
         3.20505329e-16,  6.49698969e-17,  3.27203251e-16]])